### ISSUE TITLE
Have not been able to upload my avatar because of file size being bugged

### ISSUE THREAD

**Issue by SHsuperCM** [TheOneTrueZandra/Figura#32]
My avatar which is 28322 bytes displays ingame as -0.00kB. 
When trying to upload, this shows up in the logs

```
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: java.lang.NullPointerException
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10555(class_2487.java:451)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10713(class_2487.java:116)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10555(class_2487.java:458)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10713(class_2487.java:116)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10555(class_2487.java:458)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10713(class_2487.java:116)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2499.method_10713(class_2499.java:91)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10555(class_2487.java:458)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10713(class_2487.java:116)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2499.method_10713(class_2499.java:91)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10555(class_2487.java:458)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10713(class_2487.java:116)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2499.method_10713(class_2499.java:91)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10555(class_2487.java:458)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10713(class_2487.java:116)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10555(class_2487.java:458)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10713(class_2487.java:116)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2507.method_10631(class_2507.java:95)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2507.method_10628(class_2507.java:83)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2507.method_10634(class_2507.java:44)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.blancworks.figura.PlayerData.getFileSize(PlayerData.java:152)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.blancworks.figura.gui.FiguraGuiScreen.getFileSizeText(FiguraGuiScreen.java:199)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.blancworks.figura.gui.FiguraGuiScreen.lambda$click_button$6(FiguraGuiScreen.java:193)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at net.blancworks.figura.gui.FiguraGuiScreen$$Lambda$6301/974293010.run(Unknown Source)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
[16:25:03] [Worker-Main-14/INFO]: [STDERR]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: java.lang.NullPointerException
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10555(class_2487.java:451)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10713(class_2487.java:116)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10555(class_2487.java:458)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10713(class_2487.java:116)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10555(class_2487.java:458)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10713(class_2487.java:116)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2499.method_10713(class_2499.java:91)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10555(class_2487.java:458)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10713(class_2487.java:116)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2499.method_10713(class_2499.java:91)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10555(class_2487.java:458)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10713(class_2487.java:116)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2499.method_10713(class_2499.java:91)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10555(class_2487.java:458)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10713(class_2487.java:116)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10555(class_2487.java:458)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2487.method_10713(class_2487.java:116)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2507.method_10631(class_2507.java:95)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2507.method_10628(class_2507.java:83)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.minecraft.class_2507.method_10634(class_2507.java:44)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.blancworks.figura.network.FiguraNetworkManager.lambda$postModel$4(FiguraNetworkManager.java:229)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at net.blancworks.figura.network.FiguraNetworkManager$$Lambda$6304/421668926.run(Unknown Source)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
[16:25:10] [Worker-Main-14/INFO]: [STDERR]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by TheOneTrueZandra** [comment]
Could you also post the avatar files in question in a .zip?

**Comment by SHsuperCM** [comment]
https://github.com/TheOneTrueZandra/Figura/files/6229916/architect.zip

**Comment by TheOneTrueZandra** [comment]
Fixed in [this commit](https://github.com/TheOneTrueZandra/Figura/commit/75d23294b1e873908eebb9a283bdcb9331d1df62)

Transparent parts/faces via the blockbench texture option were unsupported previously.
