### ISSUE TITLE
Error keeps getting spammed in the log

### ISSUE THREAD

**Issue by bestsoft100** [TheOneTrueZandra/Figura#42]
[03:48:30] [main/INFO]: [STDERR]: java.lang.NullPointerException
[03:48:30] [main/INFO]: [STDERR]: 	at net.blancworks.figura.models.CustomModel.getMaxRenderAmount(CustomModel.java:53)
[03:48:30] [main/INFO]: [STDERR]: 	at net.blancworks.figura.models.CustomModel.render(CustomModel.java:59)
[03:48:30] [main/INFO]: [STDERR]: 	at net.minecraft.class_591.method_2828(class_591.java:607)
[03:48:30] [main/INFO]: [STDERR]: 	at net.minecraft.class_922.method_4054(class_922.java:134)
[03:48:30] [main/INFO]: [STDERR]: 	at net.minecraft.class_1007.method_4215(class_1007.java:65)
[03:48:30] [main/INFO]: [STDERR]: 	at net.minecraft.class_1007.method_3936(class_1007.java:42)
[03:48:30] [main/INFO]: [STDERR]: 	at net.minecraft.class_898.method_3954(class_898.java:261)
[03:48:30] [main/INFO]: [STDERR]: 	at net.minecraft.class_490.method_29977(class_490.java:149)
[03:48:30] [main/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1439)
[03:48:30] [main/INFO]: [STDERR]: 	at net.minecraft.class_490.method_2486(class_490.java:149)
[03:48:30] [main/INFO]: [STDERR]: 	at net.minecraft.class_490.method_2389(class_490.java:111)
[03:48:30] [main/INFO]: [STDERR]: 	at net.minecraft.class_465.method_25394(class_465.java:101)
[03:48:30] [main/INFO]: [STDERR]: 	at net.minecraft.class_485.method_25394(class_485.java:43)
[03:48:30] [main/INFO]: [STDERR]: 	at net.minecraft.class_490.method_25394(class_490.java:92)
[03:48:30] [main/INFO]: [STDERR]: 	at net.minecraft.class_757.method_3192(class_757.java:616)
[03:48:30] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1048)
[03:48:30] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:681)
[03:48:30] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:215)
[03:48:30] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03:48:30] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[03:48:30] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[03:48:30] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[03:48:30] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
[03:48:30] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
[03:48:30] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
[03:48:30] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03:48:30] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[03:48:30] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[03:48:30] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[03:48:30] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[03:48:30] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[03:48:30] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[03:48:30] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by Dolphin2Point1** [comment]
it seems like you've messed up your trust settings somehow, maybe try resetting them?

**Comment by TheOneTrueZandra** [comment]
Yeah, delete your trust settings from the Figura folder, see if that helps.

**Comment by TheOneTrueZandra** [comment]
Did not mean to close this, sorry.

**Comment by Dolphin2Point1** [comment]
either that or an invalid player uuid

**Comment by bestsoft100** [comment]
I deleted the trust settings and it still happens

**Comment by bestsoft100** [comment]
[model.zip](https://github.com/TheOneTrueZandra/Figura/files/6251792/model.zip)
I only have this model in my folder, the error only appears if my character gets rendered and if I switch to a different model and back the errors disappear

**Comment by Hibiii** [comment]
Try on 0.0.5 now, I couldn't recreate it.

**Comment by TheOneTrueZandra** [comment]
Yeah, should be fixed.
